name: Build Android APK (EAS Local)

on:
  workflow_dispatch: # Memungkinkan Anda men-trigger build secara manual dari tab Actions
  push:
    branches:
      - main # Akan jalan otomatis setiap ada perubahan di branch main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Expo & EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build APK (EAS Local)
        run: eas build --platform android --profile preview --local --non-interactive --output app-release.apk

      - name: Upload APK ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Blusukan
          path: app-release.apk
          retention-days: 7

      - name: Tampilkan di Halaman Release Utama
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app-release.apk"
          tag: "latest"
          name: "Versi Terbaru (Latest Build)"
          body: "Silakan download file APK di bawah ini (app-release.apk) untuk menginstall aplikasinya di HP Android Anda."
          allowUpdates: true
